# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  db:
    image: postgres:16
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: h3phest0$
      POSTGRES_DB: hephestos
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d hephestos" ]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/ || exit 1" ]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
    depends_on:
       db:
         condition: service_healthy
  subscriber:
      image: hephestos-web-1
      command: python manage.py subscriber.py
      environment:
        - GOOGLE_APPLICATION_CREDENTIALS=cross_sell/services/quantum-reducer-434016-m2-4a572a9a7852.json
      volumes:
        - .:/app

volumes:
   pgdata:
# secrets:
#   db-password:
#     file: db/password.txt

