# Generated by Django 5.1 on 2025-02-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('PAUSE', 'Pause'), ('COMPLETE', 'Complete'), ('RETRY', 'Retry')], max_length=50)),
                ('retry', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('FAILED', 'Failed'), ('SUCCESS', 'Success'), ('RUNNING', 'Running')], max_length=50)),
                ('workflow_data', models.JSONField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_workflow_execution',
            },
        ),
    ]
