# Generated by Django 5.1 on 2025-02-09 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedWebhooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_topic', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cross_sell_subscribed_webhooks',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cross_sell_template',
            },
        ),
        migrations.CreateModel(
            name='WebhookEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_data', models.TextField()),
                ('event_type', models.CharField(choices=[('orders/create', 'Orders Create')])),
                ('shop_domain', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cross_sell_webhook_events',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SavedTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_json', models.JSONField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_templates', to='shopify.shop', to_field='domain')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cross_sell.template')),
            ],
            options={
                'db_table': 'cross_sell_saved_template',
            },
        ),
        migrations.CreateModel(
            name='WebhookTemplateMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cross_sell.template')),
                ('webhook_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cross_sell.subscribedwebhooks')),
            ],
            options={
                'db_table': 'cross_sell_webhook_template_map',
            },
        ),
    ]
