# Generated by Django 5.1 on 2025-03-07 08:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_sell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevents',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='webhookevents',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
    ]
