# Generated by Django 5.1 on 2024-08-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_sell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(choices=[('cross_sell', 'Cross Sell')])),
                ('webhook_data', models.TextField()),
                ('shop_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'webhook',
                'abstract': False,
            },
        ),
    ]
