# Generated by Django 5.1 on 2024-08-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_sell', '0002_webhooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooks',
            name='event_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
