# Generated by Django 5.1 on 2025-03-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_sell', '0002_webhookevents_created_at_webhookevents_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookevents',
            name='order_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
