# Generated by Django 5.1 on 2025-03-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_sell', '0003_alter_webhookevents_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhooktemplatemap',
            name='webhook_id',
        ),
        migrations.RemoveField(
            model_name='webhooktemplatemap',
            name='template_id',
        ),
        migrations.AlterField(
            model_name='template',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SubscribedWebhooks',
        ),
        migrations.DeleteModel(
            name='WebhookTemplateMap',
        ),
    ]
