# Generated by Django 5.1 on 2025-03-08 16:58

from django.db import migrations


class Migration(migrations.Migration):

    def insert_default_data(apps, schema_editor):
        template = apps.get_model("cross_sell", "Template")  # Dynamically load the model

        template_name = "1. Default Template - 15m delay notification"
        template_data = {
            "task0": {
                "type": "condition",
                "properties": {
                    "condition_type": "if",
                    "operator": ">",
                    "operand1": "current_total_price",
                    "operand2": "{val}"
                },
                "next": ["task1", None]
            },
            "task1": {
                "type": "delay",
                "properties": {
                    "duration": 15,
                    "units": "m",
                },
                "next": ["task2"]
            },
            "task2": {
                "type": "integrator",
                "properties": {
                    "integrator_type": "email",
                    "config": "null"
                },
                "next": None
            }
        }

        template.objects.create(name=template_name, description=template_data)

    dependencies = [
        ('cross_sell', '0004_remove_webhooktemplatemap_webhook_id_and_more'),
    ]

    operations = [
        migrations.RunPython(insert_default_data)
    ]
