# Generated by Django 5.1 on 2025-03-08 16:58

from django.db import migrations
import json


class Migration(migrations.Migration):

    def insert_default_data(apps, schema_editor):
        template = apps.get_model("cross_sell", "Template")  # Dynamically load the model

        template_name = "1. Default Template - 15m delay notification"
        template_data = {
            "trigger": "task0",
            "tasks": {
                "task0": {
                    "id": "task0",
                    "type": "condition",
                    "properties": {
                        "condition_type": "if",
                        "conditions": [
                            {
                                "field": "current_total_price",
                                "operator": ">",
                                "value": 50  # Using a numeric value instead of string placeholder
                            }
                        ],
                        "context": {
                            "current_total_price": 0  # Default value, will be populated at runtime
                        }
                    },
                    "next": ["task1"],
                    "status": "pending",
                    "result": None
                },
                "task1": {
                    "id": "task1",
                    "type": "delay",
                    "properties": {
                        "duration": 15,
                        "units": "minutes"
                    },
                    "next": ["task2"],
                    "status": "pending",
                    "result": None
                },
                "task2": {
                    "id": "task2",
                    "type": "integration",
                    "properties": {
                        "integration_type": "email",
                        "config": {
                            "template": "order_notification",
                            "recipient": "{{customer.email}}",  # Template variable
                            "subject": "Check out these related products!",
                            "content": "We noticed you purchased some items. Here are some related products you might like."
                        }
                    },
                    "next": [],
                    "status": "pending",
                    "result": None
                }
            }
        }

        # Pass the dictionary directly to the JSONField
        template.objects.create(name=template_name, description=template_data)

    dependencies = [
        ('cross_sell', '0004_remove_webhooktemplatemap_webhook_id_and_more'),
    ]

    operations = [
        migrations.RunPython(insert_default_data)
    ]
