# Generated by Django 5.1 on 2025-04-14 21:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_sell', '0005_add_default_template_data'),
        ('shopify', '0005_customer_created_at_customer_total_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedtemplate',
            name='execution_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savedtemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='savedtemplate',
            name='last_executed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='savedtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='template',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='template',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='template',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='webhookevents',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webhookevents',
            name='processing_error',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='webhookevents',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='webhookevents',
            name='event_type',
            field=models.CharField(choices=[('orders/create', 'Orders Create')], max_length=50),
        ),
        migrations.AlterField(
            model_name='webhookevents',
            name='webhook_data',
            field=models.JSONField(),
        ),
        migrations.AddIndex(
            model_name='savedtemplate',
            index=models.Index(fields=['shop', 'is_active'], name='cross_sell__shop_id_6edd2d_idx'),
        ),
        migrations.AddIndex(
            model_name='savedtemplate',
            index=models.Index(fields=['last_executed'], name='cross_sell__last_ex_55ac88_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevents',
            index=models.Index(fields=['shop_domain', 'created_at'], name='cross_sell__shop_do_34ea05_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevents',
            index=models.Index(fields=['order_id'], name='cross_sell__order_i_e3d9c8_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevents',
            index=models.Index(fields=['processed'], name='cross_sell__process_d20617_idx'),
        ),
    ]
