# Generated by Django 5.1 on 2025-05-03 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_sell', '0006_savedtemplate_created_at_and_more'),
        ('shopify', '0005_customer_created_at_customer_total_orders_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Template',
            new_name='WorkflowTemplate',
        ),
        migrations.AlterModelTable(
            name='WorkflowTemplate',
            table='cross_sell_workflow_template',
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_json', models.JSONField()),
                ('last_executed', models.DateTimeField(null=True)),
                ('execution_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='shopify.shop', to_field='domain')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cross_sell.workflowtemplate')),
            ],
            options={
                'db_table': 'cross_sell_workflow',
            },
        ),
        migrations.DeleteModel(
            name='SavedTemplate',
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['shop', 'is_active'], name='cross_sell__shop_id_729854_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['last_executed'], name='cross_sell__last_ex_4edeee_idx'),
        ),
    ]
