# Generated by Django 5.1 on 2025-03-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='shop_customer_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='app_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
