# Generated by Django 5.1 on 2025-03-08 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0002_alter_customer_shop_customer_id_alter_order_app_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='shop',
            new_name='domain',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shop_domain',
            new_name='domain',
        ),
    ]
