# Generated by Django 5.1 on 2025-03-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0003_rename_shop_customer_domain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
