# Generated by Django 5.1 on 2025-04-14 02:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0004_remove_order_customer_order_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='total_orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_spend',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='integrator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integrator',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='integrator',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='access_token',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('domain', 'shop_customer_id')},
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('domain', 'order_id')},
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['domain', 'email'], name='shopify_cus_domain__97c204_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['shop_customer_id'], name='shopify_cus_shop_cu_f7d873_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['total_spend'], name='shopify_cus_total_s_6aa49d_idx'),
        ),
        migrations.AddIndex(
            model_name='integrator',
            index=models.Index(fields=['name'], name='shopify_int_name_ca6915_idx'),
        ),
        migrations.AddIndex(
            model_name='integrator',
            index=models.Index(fields=['is_active'], name='shopify_int_is_acti_90d993_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['domain', 'order_id'], name='shopify_ord_domain__7a0acb_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_email'], name='shopify_ord_custome_b2037e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='shopify_ord_status_e54d39_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='shopify_ord_created_ebd86c_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['domain'], name='shopify_sho_domain_a6c880_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['email'], name='shopify_sho_email_3cfd7d_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['is_active'], name='shopify_sho_is_acti_2b691d_idx'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='shopify_customer',
        ),
        migrations.AlterModelTable(
            name='order',
            table='shopify_order',
        ),
        migrations.AlterModelTable(
            name='shop',
            table='shopify_shop',
        ),
    ]
